<query> ::= <binary-expression>

<binary-expression> ::= <unary-expression> | <unary-expression> <binary-operator> <binary-expression>

<unary-expression> ::= <primary-expression> | <unary-operator> <unary-expression>

<primary-expression> ::= <identifier> | <literal> | ( <binary-expression> )

<binary-operator> ::= > | <

<unary-operator> ::= select <binary-expression>
